name: Release Charts

on:
  push:
    tags:
    - 'my-chaert-[0-9]+.[0-9]+.[0-9]+'
    - 'my-chaert-[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

env:
  CR_OWNER: sdmironov
  CR_GIT_REPO: helm
  CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-releaser:v1.4.1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    # - name: Check that the git tag matches the chart version
    #   run: |
    #     CHART_VERSION=$(yq .version charts/Chart.yaml)
    #     if [[ "${GITHUB_REF_NAME}" == "${CHART_VERSION}" ]]; then
    #       echo "Git tag: ${GITHUB_REF_NAME}"
    #       echo "Chart version: ${CHART_VERSION}"
    #       echo "OK: Git tag matches chart version"
    #     else
    #       echo "Git tag: ${GITHUB_REF_NAME}"
    #       echo "Chart version: ${CHART_VERSION}"
    #       echo "ERROR: Git tag and chart version are different"
    #       exit 1
    #     fi

    - name: Configure Git
      run: |
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    
    - name: cr
      run: |
        cr package charts/my-chart
        cr upload charts/my-chart
        mkdir .cr-index
        cr index charts/my-chart --push
